# default player health
default_player_health: 40

# how long a player will be invulnerable on respawn (ticks)
# FIXME not implemented
player_invulnerability_on_respawn: 40

# how long a player will be invulnerable on first join (ticks)
# FIXME not implemented
player_invulnerability_on_first_join: 6000

# the hour that the day will change, in server time (0-23)
# you can account for your timezone if necessary
# FIXME not implemented
day_changeover_hour: 0

# numbers of blocks of initial border
initial_border: 25000

# blocks border will shrink each day
border_shrink: 1000

# border shrink speed, in blocks per second
border_shrink_speed: 1

# primary world name
primary_world: "world"

# nether world name
nether_world: "world_nether"

# how close to the broder a player must be to be warned (blocks)
border_warning_distance: 50

# unix epoch of the server start (to calculate the day)
start_time: 1752243721

# unix epoch of when the border will stop
total_days: 14

# allow border to shrink while server is offline
# FIXME NOT IMPLEMENTED
# offline_border_shrink: false

# do not edit this manually
version: 1